export const ROUTES = {
  home: '/home',
  intelligence: '/intelligence',
  network: '/intelligence/network',
  customDashboard: '/builder',
  myTemplates: '/templates',
  modules: '/settings/modules',
  upload: '/upload',
  view: '/view',
  semanticLayer: '/semantic-layer',
  scheduledReports: '/scheduled-reports',
  audit: '/audit',
  reportDesigner: '/report-designer',
  aiInsights: '/ai-insights',
} as const;
